# Generated by Django 2.2.7 on 2019-12-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('x', models.DecimalField(blank=True, decimal_places=20, default=None, max_digits=2000, null=True)),
                ('y', models.DecimalField(blank=True, decimal_places=20, default=None, max_digits=2000, null=True)),
                ('unique_squirrel_id', models.CharField(blank=True, default=None, max_length=20, primary_key=True, serialize=False)),
                ('hectare', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('shift', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('date', models.CharField(blank=True, default=0, max_length=20, null=True)),
                ('hectare_squirrel_number', models.IntegerField(blank=True, default=0, null=True)),
                ('age', models.CharField(blank=True, default=None, max_length=8, null=True)),
                ('primary_fur_color', models.CharField(blank=True, default=None, max_length=8, null=True)),
                ('highlight_fur_color', models.CharField(blank=True, default=None, max_length=8, null=True)),
                ('combination_of_primary_and_highlight_color', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('color_notes', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('location', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('above_ground_sighter_measurement', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('specific_location', models.CharField(blank=True, default=None, help_text='specific location of squirrel', max_length=100, null=True)),
                ('running', models.BooleanField(blank=True, default=None, help_text='whether the squirrel is running', null=True)),
                ('chasing', models.BooleanField(blank=True, default=None, help_text='whether the squirrel is chasing', null=True)),
                ('climbing', models.BooleanField(blank=True, default=None, help_text='whether the squirrel is climbing', null=True)),
                ('eating', models.BooleanField(blank=True, default=None, help_text='whether the squirrel is eating', null=True)),
                ('foraging', models.BooleanField(blank=True, default=None, help_text='whether the squirrel is foraging', null=True)),
                ('other_activities', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('kuks', models.BooleanField(blank=True, default=None, help_text='whether the squirrel kuks', null=True)),
                ('quaas', models.BooleanField(blank=True, default=None, help_text='whether the squirrel quaas', null=True)),
                ('moans', models.BooleanField(blank=True, default=None, help_text='whether the squirrel moans', null=True)),
                ('tail_flags', models.BooleanField(blank=True, default=None, help_text='whether the squirrel has tail flags', null=True)),
                ('tail_twitches', models.BooleanField(blank=True, default=None, help_text='whether the squirrel has tail twitches', null=True)),
                ('approaches', models.BooleanField(blank=True, default=None, help_text='whether the squirrel approaches', null=True)),
                ('indifferent', models.BooleanField(blank=True, default=None, help_text='whether the squirrel is indifferent', null=True)),
                ('runs_from', models.BooleanField(blank=True, default=None, help_text='whether the squirrel runs from', null=True)),
                ('other_interactions', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('lat_long', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('zip_codes', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('community_districts', models.IntegerField(blank=True, default=0, null=True)),
                ('borough_boundaries', models.IntegerField(blank=True, default=0, null=True)),
                ('city_coucil_districts', models.IntegerField(blank=True, default=0, null=True)),
                ('police_precincts', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
